@host = http://localhost:5001

# Offer
## findOffers
GET {{host}}/api/v1/offers/?limit=2

###

## create
POST {{host}}/api/v1/offers
Content-Type: application/json

{
  "title": "Квартира-12345",
  "type": "apartment",
  "bedroom": 1,
  "city": {
    "name": "Cologne",
    "location": {
      "latitude": 12,
      "longitude": 1
    }
  },
  "description": "description-description",
  "goods": [],
  "host": {
    "name": "Мария Васильева",
    "email": "alex1@example.com",
    "avatarUrl": "avatar5.jpg",
    "password": "123456",
    "type": "pro"
  },
  "images": [
    "https://a.com",
    "https://a.com",
    "https://a.com",
    "https://a.com",
    "https://a.com",
    "https://a.com"
  ],
  "isPremium": true,
  "isFavorite": false,
  "location": {
    "latitude": 1,
    "longitude": 1
  },
  "previewImage": "previewImage7.jpg",
  "price": 163,
  "publicDate": "2024-02-20T12:00:00.000Z",
  "rating": 3,
  "room": 4
}

###

## show
GET {{host}}/api/v1/offers/65ca70eda83c67a5ac7d68da2

###

## update
PATCH {{host}}/api/v1/offers/65ca70eca83c67a5ac7d688c
Content-Type: application/json

{
  "bedroom": 100,
  "price": 163
}

###

## delete
DELETE {{host}}/api/v1/offers/65ca70eca83c67a5ac7d6829
Content-Type: application/json

###

## getPremium
GET {{host}}/api/v1/offers/premium/?cityId=65ca70eca83c67a5ac7d6821

###
