@host = http://localhost:5001
@offerId = 65de146c89047dbf6d3a3f69
@token = eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6ImFsZXgyM0BleGFtcGxlLmNvbSIsIm5hbWUiOiLQnNCw0YDQuNGPINCS0LDRgdC40LvRjNC10LLQsCIsImlkIjoiNjVkZTM4N2QxNTMyYjFlNjU0MThiNzk2IiwiaWF0IjoxNzA5MDYyMjk2LCJleHAiOjE3MDkyMzUwOTZ9.829pxSkXy5LPjPTPREJA2unC-avj0y6K0KswFCL55KvmnEbr75bJ95ynT06y3SGgvmhMuCk5novuw7mksgekSw

# Offer
## findOffers
GET {{host}}/offers/?limit=2

###

## show
GET {{host}}/offers/{{offerId}}

###

## create
POST {{host}}/offers
Content-Type: application/json

{
  "title": "Квартира-3",
  "type": "apartment",
  "bedroom": 1,
  "city": {
    "name": "Cologne",
    "location": {
      "latitude": 12,
      "longitude": 1
    }
  },
  "description": "description-description",
  "goods": [],
  "host": {
    "name": "Мария Васильева",
    "email": "alex1@example.com",
    "avatarUrl": "avatar5.jpg",
    "password": "123456",
    "type": "pro"
  },
  "images": [
    "https://a.com",
    "https://a.com",
    "https://a.com",
    "https://a.com",
    "https://a.com",
    "https://a.com"
  ],
  "isPremium": true,
  "isFavorite": false,
  "location": {
    "latitude": 1,
    "longitude": 1
  },
  "previewImage": "previewImage7.jpg",
  "price": 163,
  "publishDate": "2024-02-20T12:00:00.000Z",
  "rating": 3,
  "room": 4
}

###


## update
PATCH {{host}}/offers/{{offerId}}
Content-Type: application/json

{
  "bedroom": 7,
  "price": 163
}

###

## delete
DELETE {{host}}/offers/{{offerId}}
Content-Type: application/json

###

## getPremium
GET {{host}}/offers/premium/?cityId=65ca70eca83c67a5ac7d6821

###

# Favorites
## getFavorites
GET {{host}}/offers/favorites?limit=3
Authorization: Bearer {{token}}
Content-Type: application/json

###
