@host = http://localhost:5001
@offerId = 65d76e93445c9ba6ea84a855
@token = eyJhbGciOiJIUzUxMiJ9.eyJlbWFpbCI6ImFsZXgyQGV4YW1wbGUuY29tIiwibmFtZSI6ItCc0LDRgNC40Y8g0JLQsNGB0LjQu9GM0LXQstCwIiwiaWQiOiI2NWQ4ZThhNzQyN2U2ZjViODMxM2JkMDUiLCJpYXQiOjE3MDg5NzI0NzIsImV4cCI6MTcwOTE0NTI3Mn0.xNYdGIn0ogsVvjCHRTaynERWldVGrTLhMk13pj_XR6IVnB_ps4MJzOgyYpapfaO4Hd47vuwczzzykui3qshqKQ
# Review

## get
GET {{host}}/api/v1/comments/{{offerId}}

###

## create
POST {{host}}/api/v1/comments/{{offerId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "comment": "aaa12346789111",
  "publishDate": "2024-02-20T12:00:00.000Z",
  "rating": 1,
  "author": {
    "name": "Мария Васильева",
    "email": "alex1@example.com",
    "avatarUrl": "avatar5.jpg",
    "password": "123456",
    "type": "pro"
  },
  "offer": {
    "title": "Квартира-1",
    "type": "apartment",
    "bedroom": 1,
    "city": {
      "name": "Cologne",
      "location": {
        "latitude": 1,
        "longitude": 1
      }
    },
    "description": "description-description",
    "goods": [],
    "host": {
      "name": "Мария Васильева",
      "email": "a2898ef78e901df0a7e3-alexey@example.com",
      "avatarUrl": "avatar5.jpg",
      "password": "123456",
      "type": "pro"
    },
    "images": [],
    "isPremium": true,
    "isFavorite": false,
    "location": {
      "latitude": 1,
      "longitude": 1
    },
    "previewImage": "previewImage7.jpg",
    "price": 163,
    "publicDate": "2024-02-20T12:00:00.000Z",
    "rating": 3,
    "room": 4
  }
}

###
