@host = http://localhost:5001

# User
## create
POST {{host}}/api/v1/users/
Content-Type: application/json

{
  "name": "Мария Васильева",
  "email": "alex2@example.com",
  "avatarUrl": "avatar.jpg",
  "password": "123456",
  "type": "pro"
}

###

## login
POST {{host}}/api/v1/users/login/
Content-Type: application/json

{
  "email": "a1-alexey@example.com",
  "password": "123"
}

###

## upload picture
POST {{host}}/api/v1/users/65d8e8a7427e6f5b8313bd05/avatar
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/opifex/Downloads/SCR-20240123-qkui-1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
