export const LISTLIMITSCONFIG = {
  REVIEW_LIST_LIMIT: 50,
  CITY_LIST_LIMIT: 50,
  OFFERS_LIST_LIMIT: 300,
  OFFERS_LIST_LIMIT_DEFAULT: 60,
  PREMIUM_LIST_LIMIT: 3,
  FAVORITE_LIST_LIMIT: 60,
};

export const USERPROFILECONFIG = {
  AVATAR_DEFAULT_URL: 'avatar.img',
};
